stages:
  - test
  - build

test:
  image: docker-registry.prozorro.gov.ua/docker/images/node:10-alpine3.7.3
  stage: test
  tags:
    - kube-dev
  before_script:
    - apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/main/ nodejs=10.16.3-r0
    - apk add  --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/v3.7/community/ yarn=1.16.0-r0
    - apk upgrade
    - apk add chromium
    - npm install
  script:
    - npm run test:ci

build:
  stage: build
  only:
    - tags
  tags:
    - shell
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - if [[ $CI_COMMIT_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG $CI_REGISTRY_IMAGE:latest && docker push  $CI_REGISTRY_IMAGE:latest; fi
